### PR TITLE
add libicu-dev for support of CounterStrikeSharp

### PR DESCRIPTION
**Pull request by Apfelwurm**
The currently most flexible and fututre proof way (imho) of writing Server plugins is a combination of Metamod and https://github.com/roflmuffin/CounterStrikeSharp . To run CounterStrikeSharp there is a dotnet runtime included in it, but the OS needs libicu in order to use the runtime.

Before we build a new container on your base with this single dependency added, i thought i PR it and see what you are thinking about adding it in here directly.

Have a good one!

### CODE REVIEW

**Comment by Apfelwurm** [comment]
converted back to draft, since there might be a way to remove the dependency for CounterStrikeSharp, going to investigate that later today

**Comment by joedwards32** [comment]
Hi @Apfelwurm,

Thanks for your PR. I'm happy to include `libicu-dev` in my image if it makes it easier for users to deploy mods.

I'll wait for the outcome of your investigation before merging.

**Comment by Apfelwurm** [comment]
Hey @joedwards32 thanks for the quick reply!
We are currently still investigating the Situation, because we need to test internationalisation without libicu. I'll update you / the PR as soon as possible :)

**Comment by joedwards32** [comment]
Thanks for the update :)

**Comment by Apfelwurm** [comment]
My tests also showed that libicu-dev is currently not nessecary if `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true` is setted in the env of the container. This might change as soon as someone needs stuff from the internationalization components, but for now, i think the addition is not really nessecary. Going to document that on counterstrikesharp as well :)

**Comment by Apfelwurm** [comment]
Hello, me again :D We now added the ability to localize our CounterStrikeSharp plugin recently, which now indeed brings the need for this. I think, since this will be a feture used in many plugins in the future, it would be really nice if we could have that in here.

**Comment by Apfelwurm** [comment]
again converted to draft due to more investigations into the possibility to circumvent cultures for the globalisation features :D

**Comment by Apfelwurm** [comment]
converted back, libicu is nessecary

**Comment by joedwards32** [comment]
Thanks for your contribution!

Merged and cut a new v2.0.1 release.

**Pull request merged**
